[package]
name = "iw3"
description = "Readers for Call of Duty 4 (IW3) data formats: fastfiles, iwd archives, iwi images."
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log.workspace = true
flate2.workspace = true
zip.workspace = true
