//! The IW3 struct layouts and serialisation rules, generated by
//! `tools/gen_schema.py` into `schema.json`.

use serde::Deserialize;
use std::collections::HashMap;
use std::sync::OnceLock;

#[derive(Deserialize, Debug)]
pub struct Schema {
    pub types: HashMap<String, TypeDef>,
    pub enums: HashMap<String, i64>,
    pub rules: HashMap<String, Rules>,
    /// Struct name -> OAT asset name.
    pub assets: HashMap<String, String>,
}

#[derive(Deserialize, Debug)]
pub struct TypeDef {
    pub kind: String,
    #[serde(default)]
    pub size: u32,
    #[serde(default)]
    pub align: u32,
    #[serde(default)]
    pub members: Vec<Member>,
    /// typedef target
    #[serde(default)]
    pub of: Option<String>,
    #[serde(default)]
    pub ptr: u32,
    #[serde(default)]
    pub arr: Vec<u32>,
    #[serde(default)]
    pub force_align: Option<u32>,
}

#[derive(Deserialize, Debug)]
pub struct Member {
    pub name: Option<String>,
    #[serde(rename = "type")]
    pub ty: String,
    pub ptr: u32,
    pub arr: Vec<u32>,
    #[serde(default)]
    pub pointee_arr: Vec<u32>,
    #[serde(default)]
    pub offset: u32,
    #[serde(default)]
    pub size: u32,
    #[serde(default)]
    pub bits: Option<u32>,
    #[serde(default)]
    pub bit_offset: u32,
    #[serde(default)]
    pub anon: bool,
}

#[derive(Deserialize, Debug, Default)]
pub struct Rules {
    #[serde(rename = "type", default)]
    pub ty: TypeRules,
    #[serde(default)]
    pub members: HashMap<String, MemberRules>,
}

#[derive(Deserialize, Debug, Default)]
pub struct TypeRules {
    pub block: Option<String>,
    pub reorder: Option<Vec<String>>,
    pub allocalign: Option<u32>,
}

#[derive(Deserialize, Debug, Default, Clone)]
pub struct MemberRules {
    #[serde(default)]
    pub string: bool,
    #[serde(default)]
    pub reusable: bool,
    #[serde(default)]
    pub scriptstring: bool,
    pub count: Option<String>,
    pub condition: Option<String>,
    pub arraysize: Option<String>,
    pub block: Option<String>,
    pub allocalign: Option<String>,
    pub assetref: Option<String>,
}

pub fn schema() -> &'static Schema {
    static S: OnceLock<Schema> = OnceLock::new();
    S.get_or_init(|| serde_json::from_str(include_str!("schema.json")).expect("valid schema.json"))
}

/// A member's type after following typedefs.
#[derive(Clone, Debug)]
pub struct Resolved {
    /// Struct, union or primitive name.
    pub base: String,
    pub ptr: u32,
    /// Array dimensions contributed by typedefs (e.g. `ByteVec`).
    pub arr: Vec<u32>,
    pub align: Option<u32>,
}

impl Schema {
    pub fn resolve(&self, name: &str) -> Resolved {
        let mut r = Resolved { base: name.to_owned(), ptr: 0, arr: Vec::new(), align: None };
        while let Some(t) = self.types.get(&r.base) {
            if t.kind != "typedef" {
                break;
            }
            r.ptr += t.ptr;
            r.arr.extend(&t.arr);
            if r.align.is_none() {
                r.align = t.force_align;
            }
            r.base = t.of.clone().unwrap_or_default();
            if t.ptr > 0 {
                break;
            }
        }
        r
    }

    pub fn prim_size(name: &str) -> Option<u32> {
        Some(match name {
            "char" | "uchar" | "bool" | "int8_t" | "uint8_t" | "void" => 1,
            "short" | "ushort" | "int16_t" | "uint16_t" => 2,
            "int" | "uint" | "int32_t" | "uint32_t" | "long" | "float" => 4,
            "double" | "int64_t" | "uint64_t" | "__int64" => 8,
            _ => return None,
        })
    }

    pub fn is_record(&self, name: &str) -> bool {
        self.types.get(name).is_some_and(|t| t.kind == "struct" || t.kind == "union")
    }

    /// (size, align) of a resolved type, ignoring pointers.
    pub fn size_align(&self, base: &str) -> (u32, u32) {
        if let Some(s) = Self::prim_size(base) {
            return (s, s);
        }
        match self.types.get(base) {
            Some(t) => (t.size, t.align.max(1)),
            None => (4, 4),
        }
    }

    pub fn asset_struct(&self, base: &str) -> bool {
        self.assets.contains_key(base)
    }
}
